-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 00:02:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema medipet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medipet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medipet` DEFAULT CHARACTER SET utf8 ;
USE `medipet` ;

-- -----------------------------------------------------
-- Table `medipet`.`atencion_medica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`atencion_medica` ;

CREATE TABLE IF NOT EXISTS `medipet`.`atencion_medica` (
  `atencion_fechaAtencion` DATE NOT NULL,
  `atencion_rut_cliente` VARCHAR(11) NOT NULL,
  `atencion_tipo_mascota` INT(11) NOT NULL,
  `atencion_rut_medico` VARCHAR(11) NOT NULL,
  `atencion_rut_usuario` VARCHAR(11) NOT NULL,
  `atencion_descrip` VARCHAR(50) NOT NULL,
  `atencion_cod` INT(11) NOT NULL AUTO_INCREMENT,
  `atencion_diagnostico` VARCHAR(100) NULL DEFAULT NULL,
  `atencion_procedi` VARCHAR(100) NULL DEFAULT NULL,
  `atencion_total` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`atencion_cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medipet`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`cliente` ;

CREATE TABLE IF NOT EXISTS `medipet`.`cliente` (
  `cliente_rut` VARCHAR(11) NOT NULL,
  `cliente_nombre` VARCHAR(30) NOT NULL,
  `cliente_direccion` VARCHAR(40) NOT NULL,
  `cliente_fechaNacimiento` DATE NOT NULL,
  `cliente_email` VARCHAR(40) NOT NULL,
  `cliente_genero` VARCHAR(1) NOT NULL,
  `cliente_cod` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`cliente_cod`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medipet`.`tipo_mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`tipo_mascota` ;

CREATE TABLE IF NOT EXISTS `medipet`.`tipo_mascota` (
  `cod_tipo_mascota` INT(11) NOT NULL AUTO_INCREMENT,
  `descrip_tipo_mascota` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_tipo_mascota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medipet`.`mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`mascota` ;

CREATE TABLE IF NOT EXISTS `medipet`.`mascota` (
  `mascota_cod` INT(11) NOT NULL AUTO_INCREMENT,
  `mascota_rut_cliente` VARCHAR(11) NOT NULL,
  `mascota_tipo` INT(11) NOT NULL,
  `mascota_nombre` VARCHAR(30) NOT NULL,
  `mascota_fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`mascota_cod`),
  INDEX `FK_mascota` (`mascota_tipo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medipet`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`perfil` ;

CREATE TABLE IF NOT EXISTS `medipet`.`perfil` (
  `perfil_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil_descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`perfil_codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;
INSERT INTO perfil VALUES (null,'Administrador');

-- -----------------------------------------------------
-- Table `medipet`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medipet`.`usuario` ;

CREATE TABLE IF NOT EXISTS `medipet`.`usuario` (
  `usuario_rut` VARCHAR(11) NOT NULL,
  `usuario_nombre` VARCHAR(20) NOT NULL,
  `usuario_fechaNacimiento` DATE NOT NULL,
  `usuario_email` VARCHAR(40) NOT NULL,
  `usuario_clave` VARCHAR(20) NOT NULL,
  `usuario_tipo_perfil` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`usuario_id`),
  INDEX `FK_usuario` (`usuario_tipo_perfil` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
